### ISSUE TITLE
Can't work with `F.interpolate`

### ISSUE THREAD

**Issue by DachunKai** [sovrasov/flops-counter.pytorch#119]
The model I test is a recurrent model [BasicVSR](https://github.com/XPixelGroup/BasicSR/blob/master/basicsr/archs/basicvsr_arch.py#L12-L98). And because the network need the input with shape [T, C, H, W], where T is the temporal dimension. So I custom the input_constructor:
```python
def prepare_vsr_input(resolution):
    """Prepares the input for the VSR model based on the given resolution.

    Args:
        resolution (tuple): Expected to be of the form (T, C, H, W).

    Returns:
        dict: A dictionary containing the input tensor.
    """
    x = torch.FloatTensor(1, 10, *resolution)
    return dict(x=x)
```
Then I test with following manner:
```python
    from ptflops import get_model_complexity_info
    net = BasicVSR(num_feat=12, num_block=2, spynet_path=None)

    macs, params = get_model_complexity_info(net, input_res=(3, 64, 64),
                                              input_constructor=prepare_vsr_input,
                                              as_strings=True, print_per_layer_stat=False)

    print(macs, params)
```
But it seems the flops calcuation can't work with `F.interpolate` function in [basicvsr_arch.py#L94](https://github.com/XPixelGroup/BasicSR/blob/master/basicsr/archs/basicvsr_arch.py#L94). **How to solve it? Can anyone help me?**

Following is the complete bug:
```shell
Traceback (most recent call last):
  File "/home/kaidc/miniconda3/envs/basic/lib/python3.7/site-packages/ptflops/pytorch_engine.py", line 60, in get_flops_pytorch
    _ = flops_model(**batch)
  File "/home/kaidc/miniconda3/envs/basic/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1120, in _call_impl
    result = forward_call(*input, **kwargs)
  File "/home/kaidc/code/LMVSR/basicsr/archs/basicvsr_arch.py", line 64, in forward
    flows_forward, flows_backward = self.get_flow(x)
  File "/home/kaidc/code/LMVSR/basicsr/archs/basicvsr_arch.py", line 52, in get_flow
    flows_backward = self.spynet(x_1, x_2).view(b, n - 1, 2, h, w)
  File "/home/kaidc/miniconda3/envs/basic/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/kaidc/code/LMVSR/basicsr/archs/spynet_arch.py", line 88, in forward
    ref = F.interpolate(input=ref, size=(h_floor, w_floor), mode='bilinear', align_corners=False)
  File "/home/kaidc/miniconda3/envs/basic/lib/python3.7/site-packages/ptflops/pytorch_engine.py", line 335, in __call__
    flops = self.handler(*args, **kwds)
  File "/home/kaidc/miniconda3/envs/basic/lib/python3.7/site-packages/ptflops/pytorch_ops.py", line 315, in _interpolate_functional_flops_hook
    input = args[0]
IndexError: tuple index out of range
Traceback (most recent call last):
  File "tests/test_archs/test_basicvsr_arch.py", line 86, in <module>
    test_basicvsr()
  File "tests/test_archs/test_basicvsr_arch.py", line 38, in test_basicvsr
    as_strings=True, print_per_layer_stat=False)
  File "/home/kaidc/miniconda3/envs/basic/lib/python3.7/site-packages/ptflops/flops_counter.py", line 45, in get_model_complexity_info
    precision=output_precision
  File "/home/kaidc/miniconda3/envs/basic/lib/python3.7/site-packages/ptflops/utils.py", line 12, in flops_to_string
    if flops // 10**9 > 0:
TypeError: unsupported operand type(s) for //: 'NoneType' and 'int'
```

**Comment by sovrasov** [comment]
As a quick fix I'd suggest to change ` ref = F.interpolate(input=ref, size=(h_floor, w_floor), mode='bilinear', align_corners=False)`  to ` ref = F.interpolate(ref, size=(h_floor, w_floor), mode='bilinear', align_corners=False)`

**Comment by DachunKai** [comment]
Thanks a lot! It works for me😄
