### ISSUE TITLE
Fail to install the newest version

### ISSUE THREAD

**Issue by hcidspace** [sovrasov/flops-counter.pytorch#129]
Output error message while trying to install the newest version of the ptflops package using the `pip install ptflops` command.
```
Collecting ptflops
  Using cached ptflops-0.7.2.tar.gz (14 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [12 lines of output]
      Traceback (most recent call last):
        File "<string>", line 36, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-qu75lhzr/ptflops_f0f8411fd16a41108044e46c09624023/setup.py", line 21, in <module>
          TEST_BASE_EXTRAS = (SETUP_DIR / 'test_requirements.txt').read_text()
        File "/opt/conda/lib/python3.7/pathlib.py", line 1221, in read_text
          with self.open(mode='r', encoding=encoding, errors=errors) as f:
        File "/opt/conda/lib/python3.7/pathlib.py", line 1208, in open
          opener=self._opener)
        File "/opt/conda/lib/python3.7/pathlib.py", line 1063, in _opener
          return self._accessor.open(self, flags, mode)
      FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-install-qu75lhzr/ptflops_f0f8411fd16a41108044e46c09624023/test_requirements.txt'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.
```

**Comment by sovrasov** [comment]
Thanks for reporting! Fix was uploaded https://pypi.org/project/ptflops/
