### ISSUE TITLE
not suport two input image network?

### ISSUE THREAD

**Issue by wikiwen** [sovrasov/flops-counter.pytorch#14]

**Comment by sovrasov** [comment]
Try to use the `input_constructor` argument:
```python
class Siamese(nn.Module):
    def __init__(self):
        super(Siamese, self).__init__()
        self.conv1 = nn.Conv2d(1, 10, 3, 1)
        self.conv2 = nn.Conv2d(1, 10, 3, 1)

    def forward(self, x):
        # assume x is a list
        return self.conv1(x[0]) + self.conv2(x[1])

def prepare_input(resolution):
    x1 = torch.FloatTensor(1, *resolution)
    x2 = torch.FloatTensor(1, *resolution)
    return dict(x = [x1, x2])

if __name__ == '__main__':
    model = Siamese()
    flops, params = get_model_complexity_info(model, input_res=(1, 224, 224), 
                                              input_constructor=prepare_input,
                                              as_strings=True, print_per_layer_stat=False)
    print('      - Flops:  ' + flops)
    print('      - Params: ' + params)

```

**Comment by wikiwen** [comment]
> Try to use the `input_constructor` argument:
> 
> ```python
> class Siamese(nn.Module):
>     def __init__(self):
>         super(Siamese, self).__init__()
>         self.conv1 = nn.Conv2d(1, 10, 3, 1)
>         self.conv2 = nn.Conv2d(1, 10, 3, 1)
> 
>     def forward(self, x):
>         # assume x is a list
>         return self.conv1(x[0]) + self.conv2(x[1])
> 
> def prepare_input(resolution):
>     x1 = torch.FloatTensor(1, *resolution)
>     x2 = torch.FloatTensor(1, *resolution)
>     return dict(x = [x1, x2])
> 
> if __name__ == '__main__':
>     model = Siamese()
>     flops, params = get_model_complexity_info(model, input_res=(1, 224, 224), 
>                                               input_constructor=prepare_input,
>                                               as_strings=True, print_per_layer_stat=False)
>     print('      - Flops:  ' + flops)
>     print('      - Params: ' + params)
> ```

Thanks~~it works！！

**Comment by chyohoo** [comment]
what if two inputs have different sizes?

**Comment by sovrasov** [comment]
@chyohoo in that case you can ignore the `resolution` parameter and use custom shapes:
```python
def prepare_input(resolution):
    x1 = torch.FloatTensor(1, 3, 224, 224)
    x2 = torch.FloatTensor(1, 3, 128, 128)
    return dict(x = [x1, x2])
```

**Comment by JamesLee789** [comment]
> @chyohoo in that case you can ignore the `resolution` parameter and use custom shapes:
> 
> ```python
> def prepare_input(resolution):
>     x1 = torch.FloatTensor(1, 3, 224, 224)
>     x2 = torch.FloatTensor(1, 3, 128, 128)
>     return dict(x = [x1, x2])
> ```




Hi. I tried to implement the calculation following your advice,

def prepare_input(resolution):
  x = torch.FloatTensor(1, 3, 224, 224)
  depth = torch.FloatTensor(1, 1, 224, 224)
  return dict(x=[x, depth])

...

  flops, macs, params = get_model_complexity_info(model, input_res=((1, 3, 224, 224),(1, 1, 224, 224)),input_constructor=prepare_input,as_strings=True,print_per_layer_stat=True, verbose=True)
 

However,I got the error.

Warning: module Softmax is treated as a zero-op.
Warning: module PAFEM is treated as a zero-op.
Warning: module DANet is treated as a zero-op.
Traceback (most recent call last):
  File "get_model_complexity_info.py", line 18, in <module>
    flops, macs, params = get_model_complexity_info(model, input_res=((1, 3, 384, 384),(1, 1, 384, 384)),input_constructor=prepare_input,
  File "/home/user/software/anaconda3/lib/python3.8/site-packages/ptflops/flops_counter.py", line 34, in get_model_complexity_info
    _ = flops_model(**input)
  File "/home/user/software/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
TypeError: forward() missing 1 required positional argument: 'depth'


How could I fix it?  Many thanks.

**Comment by sovrasov** [comment]
Hi! Take a look at the `forward` method of my test model: it assumes `x` to be a list, whereas your model may require a different input format as well as different arguments besides `x`. General suggestion here is to preserve input args and their layout in `prepare_input`.
My guess is your forward method looks like this: `def forwrd(self, x, depth)`. If so, you have to add `depth` argument also:
```
def prepare_input(resolution):
  x = torch.FloatTensor(1, 3, 224, 224)
  depth = torch.FloatTensor(1, 1, 224, 224)
  return dict(x=x, depth=depth)
```

**Comment by JamesLee789** [comment]
> > @chyohoo in that case you can ignore the `resolution` parameter and use custom shapes:
> > ```python
> > def prepare_input(resolution):
> >     x1 = torch.FloatTensor(1, 3, 224, 224)
> >     x2 = torch.FloatTensor(1, 3, 128, 128)
> >     return dict(x = [x1, x2])
> > ```
> 
> Hi. I tried to implement the calculation following your advice,
> 
> def prepare_input(resolution):
> x = torch.FloatTensor(1, 3, 224, 224)
> depth = torch.FloatTensor(1, 1, 224, 224)
> return dict(x=[x, depth])
> 
> ...
> 
> flops, macs, params = get_model_complexity_info(model, input_res=((1, 3, 224, 224),(1, 1, 224, 224)),input_constructor=prepare_input,as_strings=True,print_per_layer_stat=True, verbose=True)
> 
> However,I got the error.
> 
> Warning: module Softmax is treated as a zero-op.
> Warning: module TestNet is treated as a zero-op.
> Traceback (most recent call last):
> File "get_model_complexity_info.py", line 18, in
> flops, macs, params = get_model_complexity_info(model, input_res=((1, 3, 384, 384),(1, 1, 384, 384)),input_constructor=prepare_input,
> File "/home/user/software/anaconda3/lib/python3.8/site-packages/ptflops/flops_counter.py", line 34, in get_model_complexity_info
> _ = flops_model(**input)
> File "/home/user/software/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
> result = self.forward(*input, **kwargs)
> TypeError: forward() missing 1 required positional argument: 'depth'
> 
> How could I fix it? Many thanks.

Thanks for your prompt reply! It works now.

**Comment by hj611** [comment]
Does batchsize have to be 1? Can you customize the batch size? I tried your prepare_input and got the following error:
   input = input_constructor(input_res)
TypeError: 'dict' object is not callable

**Comment by sovrasov** [comment]
Hi! If you have an ordinary model that consumes only one input tensor x, the following would work for you:
```
bs = 2
input_constructor = lambda _: {"x":  torch.FloatTensor(bs, 3, 224, 224)}
    macs, params = get_model_complexity_info(net, (3, 224, 224),
                                             as_strings=True,
                                             input_constructor=input_constructor,
                                             print_per_layer_stat=True,
                                             ost=ost)
```
