### ISSUE TITLE
Adding mobilenetv3 or googlenet will cause the following bugs, can you give some suggestions

### ISSUE THREAD

**Issue by chuanfuye** [sovrasov/flops-counter.pytorch#49]
Traceback (most recent call last):
  File "/home/xiaofei/my_project/SiamTrackers/compute_params/flops-counter.pytorch/sample.py", line 35, in <module>
    net = pt_models[args.model]()
  File "/home/xiaofei/anaconda3/envs/siamtracker/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
TypeError: forward() missing 1 required positional argument: 'x'

thank you

**Comment by sovrasov** [comment]
Hi! The provided information is not enough to reproduce the bug. Please give a minimal complete example that reproduces the issue. May be #14 will help you.

**Comment by chuanfuye** [comment]
```
import sys
import argparse

import torchvision.models as models
import torch

from ptflops import get_model_complexity_info

pt_models = {'resnet18': models.resnet18,
             'resnet50': models.resnet50,
             'resnet151':models.resnet152,
             'alexnet': models.alexnet,
             'vgg16': models.vgg16,
             'squeezenet': models.squeezenet1_0,
             'densenet': models.densenet161,
             'inception': models.inception_v3,
             'shufflenetv2':models.shufflenet_v2_x1_0(),
             'googlenet':models.googlenet(),
             'mobilenet':models.mobilenet_v2()}

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='ptflops sample script')
    parser.add_argument('--device', type=int, default=0,
                        help='Device to store the model.')
    parser.add_argument('--model', choices=list(pt_models.keys()),
                        type=str, default='googlenet')
    parser.add_argument('--result', type=str, default=None)
    args = parser.parse_args()

    if args.result is None:
        ost = sys.stdout
    else:
        ost = open(args.result, 'w')

    net = pt_models[args.model]()

    if torch.cuda.is_available():
        net.cuda(device=args.device)

    macs, params = get_model_complexity_info(net, (3, 224, 224),
                                             as_strings=True,
                                             print_per_layer_stat=True,
                                             ost=ost)
    print('{:<30}  {:<8}'.format('Computational complexity: ', macs))
    print('{:<30}  {:<8}'.format('Number of parameters: ', params))
```
Thank you for your replyWhen I run resnet or alexnet, this is OK, but running mobilenet or Googlenet will display the above bug

**Comment by sovrasov** [comment]
Dict with models is supposed to contain types, not objects:
Try `'googlenet':models.googlenet(),` -> `'googlenet':models.googlenet,` and so on.

**Comment by chuanfuye** [comment]
thank you very much,It worked well
